#!/usr/bin/env bash
# Install a Tailscale-only ntfy server on this host.
# Does not deploy the glasses-server fork. Does not bind a public interface.
# Does not print topic or token values.
set -euo pipefail

PORT="${NTFY_PORT:-2586}"
PROFILE="${HERMES_PROFILE:-eve}"
HERMES_HOME="${HERMES_HOME:-$HOME/.hermes}"
ENV_FILE="${NTFY_ENV_FILE:-$HERMES_HOME/profiles/$PROFILE/ntfy.env}"

usage() {
  cat <<'EOF'
Usage: ./scripts/install-ntfy-tailscale.sh

Installs or reconfigures ntfy so it listens only on this machine's Tailscale
IPv4 address. Writes Hermes env vars to a 0600 file and never prints them.

Environment:
  NTFY_PORT          listen port (default 2586)
  HERMES_PROFILE     profile name for the env snippet (default eve)
  HERMES_HOME        Hermes home (default ~/.hermes)
  NTFY_ENV_FILE      override path for the 0600 env snippet
  NTFY_LISTEN_IP     skip Tailscale detection and use this IPv4
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

is_tailscale_ipv4() {
  local ip="$1"
  [[ "$ip" =~ ^100\.(6[4-9]|[7-9][0-9]|1[0-1][0-9]|12[0-7])\.[0-9]+\.[0-9]+$ ]]
}

reject_public_bind() {
  local ip="$1"
  case "$ip" in
    ""|0.0.0.0|"::"|'*')
      echo "refusing to bind ntfy on a public wildcard ($ip)" >&2
      exit 1
      ;;
  esac
  if [[ "$ip" == 127.* ]]; then
    echo "refusing loopback-only ntfy; the iPhone needs the Tailscale address" >&2
    exit 1
  fi
}

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "missing required command: $1" >&2
    exit 1
  }
}

need_cmd sudo
need_cmd curl
need_cmd install
need_cmd openssl

LISTEN_IP="${NTFY_LISTEN_IP:-}"
if [[ -z "$LISTEN_IP" ]]; then
  need_cmd tailscale
  LISTEN_IP="$(tailscale ip -4 | head -n1 | tr -d '[:space:]')"
fi

if [[ -z "$LISTEN_IP" ]]; then
  echo "could not determine a Tailscale IPv4; is tailscaled up?" >&2
  exit 1
fi
reject_public_bind "$LISTEN_IP"
if ! is_tailscale_ipv4 "$LISTEN_IP"; then
  echo "refusing non-Tailscale listen address: $LISTEN_IP" >&2
  exit 1
fi

install_ntfy_deb() {
  local arch
  arch="$(dpkg --print-architecture)"
  case "$arch" in
    amd64|arm64|armhf) ;;
    *)
      echo "unsupported dpkg architecture for the ntfy apt repo: $arch" >&2
      exit 1
      ;;
  esac
  sudo mkdir -p /etc/apt/keyrings
  sudo curl -fsSL -o /etc/apt/keyrings/ntfy.gpg https://archive.ntfy.sh/apt/keyring.gpg
  sudo apt-get install -y apt-transport-https
  echo "deb [arch=${arch} signed-by=/etc/apt/keyrings/ntfy.gpg] https://archive.ntfy.sh/apt stable main" \
    | sudo tee /etc/apt/sources.list.d/ntfy.list >/dev/null
  sudo apt-get update
  sudo apt-get install -y ntfy
}

if ! command -v ntfy >/dev/null 2>&1; then
  if command -v apt-get >/dev/null 2>&1 && command -v dpkg >/dev/null 2>&1; then
    install_ntfy_deb
  else
    echo "ntfy is not installed and this host is not Debian/Ubuntu. Install ntfy first, then rerun." >&2
    exit 1
  fi
fi

sudo mkdir -p /etc/ntfy /var/cache/ntfy /var/lib/ntfy
if id ntfy >/dev/null 2>&1; then
  sudo chown ntfy:ntfy /var/cache/ntfy /var/lib/ntfy
fi

# Keep an existing topic/token if we already wrote one.
TOPIC=""
if [[ -f "$ENV_FILE" ]]; then
  # shellcheck disable=SC1090
  set -a
  # Values stay in this process; we never echo them.
  source "$ENV_FILE"
  set +a
  TOPIC="${NTFY_TOPIC:-}"
fi
if [[ -z "$TOPIC" ]]; then
  TOPIC="$(openssl rand -hex 16)"
fi

BASE_URL="http://${LISTEN_IP}:${PORT}"
sudo tee /etc/ntfy/server.yml >/dev/null <<EOF
# Generated by install-ntfy-tailscale.sh. Tailscale IPv4 only.
base-url: "${BASE_URL}"
listen-http: "${LISTEN_IP}:${PORT}"
listen-https: "-"
cache-file: "/var/cache/ntfy/cache.db"
attachment-cache-dir: "/var/cache/ntfy/attachments"
behind-proxy: false
enable-signup: false
enable-login: false
web-root: disable
EOF

sudo systemctl enable ntfy
sudo systemctl restart ntfy

mkdir -p "$(dirname "$ENV_FILE")"
umask 077
cat > "$ENV_FILE" <<EOF
NTFY_SERVER_URL=${BASE_URL}
NTFY_TOPIC=${TOPIC}
NTFY_PUBLISH_TOPIC=${TOPIC}
NTFY_HOME_CHANNEL=${TOPIC}
EOF
chmod 600 "$ENV_FILE"

if ! curl -fsS --max-time 5 "${BASE_URL}/v1/health" >/dev/null; then
  echo "ntfy did not answer on the Tailscale address. Check: sudo systemctl status ntfy" >&2
  exit 1
fi

echo "ntfy is listening on the Tailscale IPv4 (port ${PORT})."
echo "Hermes env snippet written to ${ENV_FILE} (mode 0600; values not printed)."
echo "Next:"
echo "  1. Append that file to ~/.hermes/profiles/${PROFILE}/.env (do not commit it)."
echo "  2. Omit NTFY_ALLOWED_USERS so the topic stays outbound-only."
echo "  3. On the iPhone: ntfy app → subscribe to the topic in that file."
echo "  4. Even app → Settings → Notification → enable ntfy, popup mode ON."
echo "  5. ./scripts/install-g2-notify-skill.sh ${PROFILE}"
echo "  6. ./scripts/bootstrap-jobs.sh ${PROFILE} ntfy"
